name: nemo_vault
description: "A secure file vault for Nemo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  
  # Core Security & Auth
  local_auth: ^2.3.0 
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3 
  crypto: ^3.0.6 

  # --- NEW: Auto-Lock & Privacy Plugins ---
  # Blurs the app in Android/iOS switcher and handles Windows focus
  secure_application: ^3.1.0 
  # Detects Windows System Lock (Win+L) and Sleep states
  desktop_screenstate: ^0.0.6+1
  window_manager: ^0.3.9
  
  # File Handling
  path_provider: ^2.1.5 
  path: ^1.9.1 
  file_picker: ^10.3.8 

  # UI & Icons
  cupertino_icons: ^1.0.8 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/shield.png